### PR TITLE
Wait wait now I get it

### PR DESCRIPTION
**Pull request by bazzargh**
Finally I reelized what I dun wrong

### CODE REVIEW

**Comment by mmrobins** [comment]
:+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:

**Comment by notbenh** [comment]
unacceptable.

On Thu, Apr 23, 2015 at 7:27 PM, Matt Robinson <notifications@github.com>
wrote:

> [image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:][image:
> : +1:][image: :+1:][image: :+1:][image: :+1:][image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notbenh/dont-fucking-send-me-patches-I-hate-you-all/pull/10#issuecomment-95778203>
> .
>



-- 
benh~

http://about.notbenh.info

Stability is not a Regression and keep being Awesome!

**Comment by mmrobins** [comment]
I'll help resolve the merge conflicts.  Here's a link https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/

**Comment by mmrobins** [comment]
Here's another https://www.youtube.com/user/mergeconflict

**Comment by notbenh** [comment]
~meh~ how's that pitcher doing?

On Thu, Apr 23, 2015 at 7:53 PM, Matt Robinson <notifications@github.com>
wrote:

> Here's another https://www.youtube.com/user/mergeconflict
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notbenh/dont-fucking-send-me-patches-I-hate-you-all/pull/10#issuecomment-95781945>
> .
>



-- 
benh~

http://about.notbenh.info

Stability is not a Regression and keep being Awesome!

**Comment by mmrobins** [comment]
Looks like it's my turn

**Comment by notbenh** [comment]
game on

On Thu, Apr 23, 2015 at 8:11 PM, Matt Robinson <notifications@github.com>
wrote:

> Looks like it's my turn
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notbenh/dont-fucking-send-me-patches-I-hate-you-all/pull/10#issuecomment-95783826>
> .
>



-- 
benh~

http://about.notbenh.info

Stability is not a Regression and keep being Awesome!

**Pull request closed without merging**
