### PR TITLE
minor speling crection

### PR DESCRIPTION
**Pull request by bazzargh**
I just realised you misspelled a bunch of things about how much you love pull requests.

Also, it's your round.

### CODE REVIEW

**Comment by mmrobins** [comment]
:+1:

**Comment by notbenh** [comment]
cauz ov spel isuz I haz applyd dis pthc

**Comment by mmrobins** [comment]
This is causing failures for me now, can you revert?

**Comment by notbenh** [comment]
I could but I have other things that I would rather be doing... file a pull req.

**Comment by mmrobins** [comment]
Fair enough.  Are you buying the next round?  Or am I?

**Comment by notbenh** [comment]
wait you can see me! creepy... as for the next round I'll vote for the
dopplebock again if I'm buying.

On Thu, Apr 23, 2015 at 7:03 PM, Matt Robinson <notifications@github.com>
wrote:

> Fair enough. Are you buying the next round? Or am I?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notbenh/dont-fucking-send-me-patches-I-hate-you-all/pull/7#issuecomment-95773820>
> .
>



-- 
benh~

http://about.notbenh.info

Stability is not a Regression and keep being Awesome!

**Pull request merged**
